# Generated by Django 5.2.9 on 2025-12-05 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(help_text='The domain being reported on (e.g. google.com)', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForensicSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateTimeField()),
                ('subject', models.TextField(null=True)),
                ('source_ip', models.GenericIPAddressField(null=True)),
                ('feedback_report', models.JSONField()),
                ('domain_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.domainentity')),
            ],
        ),
        migrations.AddField(
            model_name='domainentity',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.organization'),
        ),
        migrations.CreateModel(
            name='DmarcReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('source_ip', models.GenericIPAddressField()),
                ('source_hostname', models.TextField(blank=True, null=True)),
                ('source_base_domain', models.TextField(blank=True, null=True)),
                ('country_code', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField()),
                ('disposition', models.TextField()),
                ('dkim_aligned', models.BooleanField()),
                ('spf_aligned', models.BooleanField()),
                ('header_from', models.TextField()),
                ('envelope_from', models.TextField(null=True)),
                ('dkim_domains', models.JSONField(default=list)),
                ('auth_results', models.JSONField()),
                ('domain_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.domainentity')),
            ],
            options={
                'indexes': [models.Index(fields=['date_begin', 'domain_entity'], name='dashboard_d_date_be_7e7b7e_idx')],
            },
        ),
    ]
