# Generated by Django 5.2.9 on 2025-12-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_create_hypertable'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmarcreport',
            name='report_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
